import pg from "pg";
import pool from "./db.js";
import bcrypt from "bcryptjs";

const seed = async () => {
  let client;
  let isDirectClient = false;

  if (process.env.DATABASE_URL) {
    const { Client } = pg;
    client = new Client({
      connectionString: process.env.DATABASE_URL,
      ssl: { rejectUnauthorized: false },
      connectionTimeoutMillis: 15000,
    });
    await client.connect();
    isDirectClient = true;
  } else {
    client = await pool.connect();
  }
  try {
    await client.query("BEGIN");

    // Site config — bank details as single source of truth in DB
    await client.query(`
      INSERT INTO site_config (key, value) VALUES
        ('bank_name', 'JPMorgan Chase'),
        ('bank_account_name', 'Moxy NYC Times Square LLC'),
        ('bank_account_number', '0042-1234567'),
        ('bank_routing_number', '021000021'),
        ('bank_swift', 'CHASUS33'),
        ('bank_iban', 'US00CHAS00210000210000000'),
        ('bank_instructions', 'Please include your Booking Reference Number as the payment reference. Transfers typically take 1–2 business days.')
      ON CONFLICT (key) DO NOTHING;
    `);

    // Admin user
    const adminHash = await bcrypt.hash("Admin@Fairmont2026", 12);
    await client.query(
      `
      INSERT INTO users (first_name, last_name, email, password_hash, role, email_verified)
      VALUES ('Admin', 'Moxy', 'admin@fifahotel.com', $1, 'admin', true)
      ON CONFLICT (email) DO NOTHING;
    `,
      [adminHash],
    );

    // Room categories
    await client.query(`
      INSERT INTO room_categories (name, slug, description, display_order) VALUES
        ('Classic Room', 'classic', 'Elegantly appointed rooms with timeless décor and modern amenities.', 1),
        ('Deluxe Room', 'deluxe', 'Spacious rooms with premium furnishings and enhanced views.', 2),
        ('Junior Suite', 'junior-suite', 'Generous suites with a separate living area and luxurious appointments.', 3),
        ('Grand Suite', 'grand-suite', 'Expansive suites offering the pinnacle of Manhattan luxury.', 4),
        ('Presidential Suite', 'presidential-suite', 'Our most exclusive offering — a masterpiece of space, elegance and service.', 5)
      ON CONFLICT (slug) DO NOTHING;
    `);

    // Fetch category IDs
    const { rows: cats } = await client.query(
      "SELECT id, slug FROM room_categories",
    );
    const catMap = {};
    cats.forEach((c) => {
      catMap[c.slug] = c.id;
    });

    // Rooms
    const rooms = [
      {
        category_slug: "classic",
        name: "Classic Heritage Room",
        slug: "classic-heritage-room",
        short_description:
          "A refined retreat with castle views and heritage furnishings.",
        description:
          "Steeped in the history of Moxy NYC Times Square, the Classic Heritage Room offers a serene escape with hand-crafted furnishings, plush bedding and refined details at every turn. City or courtyard views frame your stay within the heart of Times Square.",
        price_per_night: 389,
        max_occupancy: 2,
        adults: 2,
        children: 0,
        size_sqft: 320,
        floor_level: "Floors 3–7",
        view_type: "City or Courtyard View",
        bed_type: "King or Two Doubles",
        bathroom_type:
          "Marble bathroom with deep soaking tub and separate rain shower",
        features: [
          "320 sq ft",
          "King or Two Doubles",
          "City or Courtyard View",
          "Marble Bathroom",
          "Soaking Tub",
          "Rain Shower",
          '55" 4K Smart TV',
          "Mini Bar",
          "In-room Safe",
          "Pillow Menu",
          "Turndown Service",
          "Complimentary Wi-Fi",
          "Air Conditioning",
          "Robes & Slippers",
          "Room Service",
        ],
        amenities: [
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Pillow Menu",
          "Room Service 24/7",
          "Daily Newspaper",
        ],
        images: [
          "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
      {
        category_slug: "classic",
        name: "Classic City View Room",
        slug: "classic-city-view-room",
        short_description:
          "Wake to panoramic views of the iconic Manhattan skyline.",
        description:
          "Positioned to capture the breathtaking beauty of the Manhattan skyline, this room pairs contemporary interiors with sweeping cityscape views. New York City's iconic skyline provides a living canvas that dazzles from sunrise to the glittering lights of the evening.",
        price_per_night: 429,
        max_occupancy: 2,
        adults: 2,
        children: 0,
        size_sqft: 330,
        floor_level: "Floors 5–8",
        view_type: "City Skyline View",
        bed_type: "King",
        bathroom_type: "Marble bathroom with soaking tub and walk-in shower",
        features: [
          "330 sq ft",
          "King Bed",
          "City Skyline View",
          "Marble Bathroom",
          "Soaking Tub",
          "Walk-in Shower",
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Pillow Menu",
          "Turndown Service",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },
      {
        category_slug: "deluxe",
        name: "Deluxe Times Square View Room",
        slug: "deluxe-times-square-view-room",
        short_description:
          "Iconic views of Times Square from a superbly appointed deluxe room.",
        description:
          "Few hotel rooms in New York command views as iconic as this. The Deluxe Times Square View Room faces the electric heart of Times Square directly, offering a dramatic backdrop to your stay. Upgraded furnishings, premium linens, and enhanced amenities elevate the experience.",
        price_per_night: 519,
        max_occupancy: 2,
        adults: 2,
        children: 0,
        size_sqft: 380,
        floor_level: "Floors 6–10",
        view_type: "Times Square View",
        bed_type: "King",
        bathroom_type:
          "Italian marble bathroom with dual vanity, deep soaking tub and separate rain shower",
        features: [
          "380 sq ft",
          "King Bed",
          "Times Square View",
          "Italian Marble Bathroom",
          "Dual Vanity",
          "Soaking Tub",
          "Rain Shower",
          '65" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Nespresso Machine",
          "Pillow Menu",
          "Evening Turndown",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        amenities: [
          '65" 4K Smart TV',
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Turndown Service",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
      {
        category_slug: "deluxe",
        name: "Deluxe Moxy Room",
        slug: "deluxe-moxy-room",
        short_description:
          "Our signature Deluxe offering with enhanced space and premium comforts.",
        description:
          "The Deluxe Moxy Room represents the quintessential Moxy NYC experience — spacious, beautifully appointed, and finished with the hallmark details that define the Moxy standard. Enhanced square footage allows for a more generous layout and gracious living space.",
        price_per_night: 479,
        max_occupancy: 3,
        adults: 2,
        children: 1,
        size_sqft: 420,
        floor_level: "Floors 4–9",
        view_type: "City View",
        bed_type: "King or Two Queens",
        bathroom_type:
          "Marble bathroom with soaking tub and stand-alone shower",
        features: [
          "420 sq ft",
          "King or Two Queens",
          "City View",
          "Marble Bathroom",
          "Soaking Tub",
          "Stand-alone Shower",
          '65" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Pillow Menu",
          "Nespresso Machine",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        amenities: [
          '65" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Nespresso Machine",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Turndown Service",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },
      {
        category_slug: "junior-suite",
        name: "Junior Suite",
        slug: "junior-suite",
        short_description:
          "A well-proportioned suite with a defined living area and signature Moxy service.",
        description:
          "The Junior Suite offers a harmonious blend of bedroom and living space, providing guests with room to relax and recharge in true luxury. Rich draperies, bespoke furniture pieces and meticulous craftsmanship define the character of these spacious retreats.",
        price_per_night: 749,
        max_occupancy: 3,
        adults: 2,
        children: 1,
        size_sqft: 620,
        floor_level: "Floors 5–9",
        view_type: "City or Skyline View",
        bed_type: "King",
        bathroom_type:
          "Luxury marble bathroom with dual vanity, deep soaking tub, walk-in rain shower and heated floors",
        features: [
          "620 sq ft",
          "King Bed",
          "Separate Living Area",
          "City or Skyline View",
          "Heated Marble Floors",
          "Dual Vanity",
          "Deep Soaking Tub",
          "Walk-in Rain Shower",
          '75" 4K Smart TV (x2)',
          "Wet Bar",
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Pillow Menu",
          "Evening Turndown",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Room Service 24/7",
          "Enhanced Minibar",
        ],
        amenities: [
          '75" 4K Smart TV x2',
          "Wet Bar",
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Butler Service",
          "Turndown Service",
          "Room Service 24/7",
          "Heated Floors",
        ],
        images: [
          "https://images.unsplash.com/photo-1631049421450-348ccd7f8949?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
      {
        category_slug: "grand-suite",
        name: "Grand Moxy Suite",
        slug: "grand-moxy-suite",
        short_description:
          "The Grand Moxy Suite — an incomparable standard in Manhattan luxury.",
        description:
          "Every aspect of the Grand Moxy Suite has been conceived with reverence for Moxy NYC's bold spirit and an unwavering commitment to contemporary luxury. A full living room, private dining area, and master bedroom form a self-contained world of refinement within New York's most vibrant address.",
        price_per_night: 1250,
        max_occupancy: 4,
        adults: 3,
        children: 1,
        size_sqft: 1100,
        floor_level: "Floors 8–11",
        view_type: "Times Square and Manhattan Panoramic View",
        bed_type: "King",
        bathroom_type:
          "Two full marble bathrooms, master bath with freestanding soaking tub, dual rain showers and heated floors",
        features: [
          "1,100 sq ft",
          "King Bed",
          "Full Living Room",
          "Private Dining Area",
          "Times Square & Manhattan Views",
          "2 Full Marble Bathrooms",
          "Freestanding Soaking Tub",
          "Dual Rain Showers",
          "Heated Floors",
          '85" 4K Smart TV (x3)',
          "Full Wet Bar",
          "Nespresso Premium Machine",
          "In-suite Dining",
          "Safe",
          "Pillow Menu",
          "Butler Service",
          "Evening Turndown",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        amenities: [
          '85" 4K Smart TV x3',
          "Full Wet Bar",
          "In-suite Dining",
          "Nespresso Premium",
          "Dedicated Butler",
          "Pillow Menu",
          "Robes & Slippers",
          "Heated Floors",
          "Twice-daily Housekeeping",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
      {
        category_slug: "presidential-suite",
        name: "Presidential Suite",
        slug: "presidential-suite",
        short_description:
          "New York's most prestigious address — an entire floor of unparalleled grandeur.",
        description:
          "The Presidential Suite at Moxy NYC Times Square is not merely a room — it is an event. Occupying a commanding position within the hotel, this masterpiece of design and hospitality has hosted heads of state, royalty, and the world's most discerning guests. Three bedrooms, a grand reception room, a private library, and sweeping panoramic views of Times Square, the Hudson River and the glittering Manhattan skyline define this extraordinary residence.",
        price_per_night: 4500,
        max_occupancy: 6,
        adults: 4,
        children: 2,
        size_sqft: 3200,
        floor_level: "Top Floor",
        view_type: "360° Panoramic — Times Square, Hudson River, Central Park",
        bed_type: "Three King Bedrooms",
        bathroom_type:
          "Three full luxury marble bathrooms, master bath with two freestanding soaking tubs, his-and-hers rain showers, and heated stone floors",
        features: [
          "3,200 sq ft",
          "Three King Bedrooms",
          "Grand Reception Room",
          "Private Library",
          "Private Dining Room (seats 12)",
          "360° Panoramic Views",
          "3 Luxury Marble Bathrooms",
          "Two Freestanding Soaking Tubs",
          "His & Hers Rain Showers",
          "Heated Stone Floors",
          '85" 4K Smart TV (x5)',
          "Grand Piano",
          "Full Kitchen",
          "Wine Cellar",
          "Dedicated Butler Team",
          "Private Check-in",
          "Airport Transfer Included",
          "Pillow Menu",
          "Evening Turndown",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        amenities: [
          "Grand Piano",
          "Full Kitchen",
          "Wine Cellar",
          "Dedicated Butler Team",
          "Private Check-in",
          "Airport Transfer",
          '85" 4K Smart TV x5',
          "In-suite Dining",
          "Nespresso Premium Bar",
          "Heated Stone Floors",
          "24/7 Personal Concierge",
          "Private Library",
        ],
        images: [
          "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },

      // ── ADDITIONAL CLASSIC ROOMS ──────────────────────────────────
      {
        category_slug: "classic",
        name: "Classic Twin Room",
        slug: "classic-twin-room",
        short_description:
          "Two plush beds, contemporary décor and all the hallmarks of Moxy NYC comfort.",
        description:
          "Ideal for travelling companions or families, the Classic Twin Room delivers the Moxy NYC experience with two full double beds dressed in premium linens, designer furnishings and city views. Thoughtfully designed with extra wardrobe space and dual vanity lighting.",
        price_per_night: 399,
        max_occupancy: 3,
        adults: 2,
        children: 1,
        size_sqft: 340,
        floor_level: "Floors 3–7",
        view_type: "City View",
        bed_type: "Two Double Beds",
        bathroom_type: "Marble bathroom with oversized walk-in shower",
        features: [
          "340 sq ft",
          "Two Double Beds",
          "City View",
          "Marble Bathroom",
          "Walk-in Shower",
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Pillow Menu",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        amenities: [
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1515362778563-6a8d0e44bc0b?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },
      {
        category_slug: "classic",
        name: "Classic Corner Room",
        slug: "classic-corner-room",
        short_description:
          "A coveted corner position delivers dual-aspect views over the city.",
        description:
          "The Classic Corner Room benefits from a privileged position at the building's corner, offering dual-aspect windows with sweeping views across Manhattan's skyline. Natural light floods the room throughout the day, enhancing the warm tones of the heritage-inspired interior.",
        price_per_night: 449,
        max_occupancy: 2,
        adults: 2,
        children: 0,
        size_sqft: 360,
        floor_level: "Floors 4–8",
        view_type: "Dual-aspect City Views",
        bed_type: "King",
        bathroom_type: "Marble bathroom with deep soaking tub and rain shower",
        features: [
          "360 sq ft",
          "King Bed",
          "Dual-aspect Views",
          "Marble Bathroom",
          "Soaking Tub",
          "Rain Shower",
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Nespresso Machine",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '55" 4K Smart TV',
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1505693314120-0d443867891c?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },
      {
        category_slug: "classic",
        name: "Classic Garden Court Room",
        slug: "classic-garden-court-room",
        short_description:
          "Tranquil and serene — a peaceful retreat facing the hotel's inner courtyard.",
        description:
          "For guests who seek quiet over spectacle, the Classic Garden Court Room offers a serene setting away from the city's pulse. Overlooking the hotel's private inner courtyard, this room invites genuine rest with its muted palette, soft lighting and meticulous attention to comfort.",
        price_per_night: 369,
        max_occupancy: 2,
        adults: 2,
        children: 0,
        size_sqft: 310,
        floor_level: "Floors 2–5",
        view_type: "Courtyard View",
        bed_type: "Queen or King",
        bathroom_type: "Marble bathroom with walk-in shower",
        features: [
          "310 sq ft",
          "Queen or King Bed",
          "Courtyard View",
          "Marble Bathroom",
          "Walk-in Shower",
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Pillow Menu",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1631049421450-348ccd7f8949?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },
      {
        category_slug: "classic",
        name: "Classic Accessible Room",
        slug: "classic-accessible-room",
        short_description:
          "Full Moxy luxury thoughtfully designed for accessibility and comfort.",
        description:
          "The Classic Accessible Room ensures every guest experiences the full warmth of Moxy hospitality. Designed in close collaboration with accessibility specialists, this room offers roll-in shower, widened doorways, lowered fixtures and all the premium amenities of our Classic collection — without compromise.",
        price_per_night: 389,
        max_occupancy: 2,
        adults: 2,
        children: 0,
        size_sqft: 380,
        floor_level: "Floors 2–3",
        view_type: "City or Courtyard View",
        bed_type: "King",
        bathroom_type:
          "Accessible marble bathroom with roll-in shower, grab bars, and handheld shower head",
        features: [
          "380 sq ft",
          "King Bed",
          "Roll-in Shower",
          "Grab Bars",
          "Widened Doorways",
          "Lowered Closet Rail",
          "Visual Doorbell",
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '55" 4K Smart TV',
          "Mini Bar",
          "Safe",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Roll-in Shower",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },

      // ── ADDITIONAL DELUXE ROOMS ───────────────────────────────────
      {
        category_slug: "deluxe",
        name: "Deluxe Skyline View Room",
        slug: "deluxe-skyline-view-room",
        short_description:
          "Premium Deluxe appointments meet the breathtaking Manhattan skyline.",
        description:
          "Combining the elevated finishes of our Deluxe collection with coveted Manhattan skyline views, this room is among the most sought-after in the hotel. By day, watch the city pulse with energy below; by night, witness the iconic lights of the New York skyline come alive.",
        price_per_night: 559,
        max_occupancy: 2,
        adults: 2,
        children: 0,
        size_sqft: 390,
        floor_level: "Floors 6–10",
        view_type: "Manhattan Skyline View",
        bed_type: "King",
        bathroom_type:
          "Italian marble bathroom with dual vanity, soaking tub and rain shower",
        features: [
          "390 sq ft",
          "King Bed",
          "Manhattan Skyline View",
          "Italian Marble Bathroom",
          "Dual Vanity",
          "Soaking Tub",
          "Rain Shower",
          '65" 4K Smart TV',
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Pillow Menu",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '65" 4K Smart TV',
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Turndown Service",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },
      {
        category_slug: "deluxe",
        name: "Deluxe Corner Suite",
        slug: "deluxe-corner-suite",
        short_description:
          "A sprawling corner position with dual panoramic views and suite-level finishes.",
        description:
          "The Deluxe Corner Suite occupies one of the most sought-after positions in the hotel. Wrap-around views capture both Times Square and the Manhattan skyline simultaneously, while the enlarged footprint creates a genuinely suite-like living experience within the Deluxe category.",
        price_per_night: 599,
        max_occupancy: 3,
        adults: 2,
        children: 1,
        size_sqft: 480,
        floor_level: "Floors 7–10",
        view_type: "Times Square & Manhattan Panoramic",
        bed_type: "King",
        bathroom_type:
          "Oversized marble bathroom with freestanding tub and separate walk-in shower",
        features: [
          "480 sq ft",
          "King Bed",
          "Wrap-around Panoramic Views",
          "Freestanding Soaking Tub",
          "Walk-in Shower",
          "Sitting Area",
          '65" 4K Smart TV',
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Pillow Menu",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '65" 4K Smart TV',
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Turndown Service",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
      {
        category_slug: "deluxe",
        name: "Deluxe Twin Room",
        slug: "deluxe-twin-room",
        short_description:
          "Two queen beds with Deluxe-tier appointments — ideal for families or colleagues.",
        description:
          "The Deluxe Twin Room combines the elevated finishes of the Deluxe collection with the practicality of two queen beds. Generous wardrobe space, premium soft furnishings and city views make this a popular choice for both paired travellers and small families.",
        price_per_night: 499,
        max_occupancy: 4,
        adults: 2,
        children: 2,
        size_sqft: 430,
        floor_level: "Floors 4–9",
        view_type: "City View",
        bed_type: "Two Queen Beds",
        bathroom_type: "Marble bathroom with soaking tub and walk-in shower",
        features: [
          "430 sq ft",
          "Two Queen Beds",
          "City View",
          "Marble Bathroom",
          "Soaking Tub",
          "Walk-in Shower",
          '65" 4K Smart TV',
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Pillow Menu",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '65" 4K Smart TV',
          "Mini Bar",
          "Nespresso Machine",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Turndown Service",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },

      // ── ADDITIONAL JUNIOR SUITES ──────────────────────────────────
      {
        category_slug: "junior-suite",
        name: "Junior Skyline Suite",
        slug: "junior-skyline-suite",
        short_description:
          "A beautifully proportioned suite commanding unobstructed Manhattan skyline views.",
        description:
          "The Junior Skyline Suite presents an exceptional marriage of living space and scenery. A distinct seating area faces floor-to-ceiling windows overlooking the Manhattan skyline, while the bedroom's refined appointments — including a custom king bed, premium art and bespoke lighting — create an atmosphere of quiet luxury.",
        price_per_night: 849,
        max_occupancy: 3,
        adults: 2,
        children: 1,
        size_sqft: 680,
        floor_level: "Floors 6–9",
        view_type: "Manhattan Skyline View",
        bed_type: "King",
        bathroom_type:
          "Luxury marble bathroom with dual rainfall showers, freestanding tub and heated floors",
        features: [
          "680 sq ft",
          "King Bed",
          "Separate Living Area",
          "Manhattan Skyline View",
          "Dual Rainfall Showers",
          "Freestanding Tub",
          "Heated Floors",
          '75" 4K Smart TV x2',
          "Wet Bar",
          "Nespresso Machine",
          "Safe",
          "Pillow Menu",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Butler Service",
        ],
        amenities: [
          '75" 4K Smart TV x2',
          "Wet Bar",
          "Nespresso Machine",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Butler Service",
          "Turndown Service",
          "Room Service 24/7",
          "Heated Floors",
        ],
        images: [
          "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
      {
        category_slug: "junior-suite",
        name: "Junior Times Square Suite",
        slug: "junior-times-square-suite",
        short_description:
          "Suite-level opulence with a front-row seat to Times Square.",
        description:
          "Facing Times Square directly, the Junior Times Square Suite frames one of New York's most celebrated views from a suite-sized living space. The distinct lounge area invites leisurely mornings, while the master bedroom — furnished with a bespoke king bed and custom draperies — ensures deeply restorative sleep.",
        price_per_night: 899,
        max_occupancy: 3,
        adults: 2,
        children: 1,
        size_sqft: 700,
        floor_level: "Floors 7–10",
        view_type: "Times Square View",
        bed_type: "King",
        bathroom_type:
          "Italian marble bathroom with freestanding soaking tub, double rain shower and integrated steam",
        features: [
          "700 sq ft",
          "King Bed",
          "Separate Living Area",
          "Times Square View",
          "Steam Shower",
          "Freestanding Soaking Tub",
          "Double Rain Shower",
          "Heated Floors",
          '75" 4K Smart TV x2',
          "Wet Bar",
          "Nespresso Premium",
          "Safe",
          "Pillow Menu",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Butler Service",
        ],
        amenities: [
          '75" 4K Smart TV x2',
          "Wet Bar",
          "Nespresso Premium",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Butler Service",
          "Steam Shower",
          "Heated Floors",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1631049421450-348ccd7f8949?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },
      {
        category_slug: "junior-suite",
        name: "Junior Moxy Gold Suite",
        slug: "junior-moxy-gold-suite",
        short_description:
          "Exclusive Moxy Gold floor access with dedicated lounge and concierge.",
        description:
          "The Junior Moxy Gold Suite unlocks access to the exclusive Moxy Gold private floor — a world of discreet luxury with a dedicated lounge, personalised check-in, curated breakfast and evening receptions. The suite itself combines a generous living area with the Moxy Gold standard of bespoke appointment.",
        price_per_night: 1050,
        max_occupancy: 2,
        adults: 2,
        children: 0,
        size_sqft: 720,
        floor_level: "Moxy Gold Floor (Floor 11)",
        view_type: "City & Skyline View",
        bed_type: "King",
        bathroom_type:
          "Signature marble bathroom with deep soaking tub, walk-in rain shower, dual vanity and heated floors",
        features: [
          "720 sq ft",
          "King Bed",
          "Moxy Gold Floor Access",
          "Private Gold Lounge",
          "Personalised Check-in",
          "Daily Breakfast Included",
          "Evening Reception",
          "Dual Vanity",
          "Soaking Tub",
          "Rain Shower",
          "Heated Floors",
          '75" 4K Smart TV x2',
          "Premium Wet Bar",
          "Nespresso Gold",
          "Safe",
          "Pillow Menu",
          "Butler Service",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '75" 4K Smart TV x2',
          "Premium Wet Bar",
          "Nespresso Gold",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Moxy Gold Lounge",
          "Personalised Butler",
          "Daily Breakfast",
          "Evening Reception",
          "Heated Floors",
        ],
        images: [
          "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },

      // ── ADDITIONAL GRAND SUITES ───────────────────────────────────
      {
        category_slug: "grand-suite",
        name: "Grand Skyline Suite",
        slug: "grand-skyline-suite",
        short_description:
          "A grand residence poised above Manhattan with floor-to-ceiling panoramas.",
        description:
          "The Grand Skyline Suite is among the most photographed in New York. Its double-height windows span the full width of the skyline-facing façade, creating a living panorama at every hour of the day. The suite's grand proportions accommodate a full dining table, two seating areas and a master bedroom of regal refinement.",
        price_per_night: 1450,
        max_occupancy: 4,
        adults: 3,
        children: 1,
        size_sqft: 1250,
        floor_level: "Floors 9–11",
        view_type: "Manhattan Skyline Panoramic View",
        bed_type: "King",
        bathroom_type:
          "Two full marble bathrooms, master featuring freestanding tub, steam shower and heated stone floors",
        features: [
          "1,250 sq ft",
          "King Bed",
          "Full Living Room",
          "Dining Area",
          "Manhattan Skyline Panoramic",
          "2 Full Marble Bathrooms",
          "Steam Shower",
          "Freestanding Soaking Tub",
          "Heated Stone Floors",
          '85" 4K Smart TV x3',
          "Full Wet Bar",
          "Nespresso Premium",
          "Safe",
          "Pillow Menu",
          "Butler Service",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
          "Room Service 24/7",
        ],
        amenities: [
          '85" 4K Smart TV x3',
          "Full Wet Bar",
          "Nespresso Premium",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Dedicated Butler",
          "Steam Shower",
          "Heated Floors",
          "Twice-daily Housekeeping",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
      {
        category_slug: "grand-suite",
        name: "Grand Times Square Suite",
        slug: "grand-times-square-suite",
        short_description:
          "A palatial residence directly facing Times Square with private dining and butler.",
        description:
          "The Grand Times Square Suite commands the most iconic sightline in New York — a direct, uninterrupted view of the Times Square marquee. This palatial residence features a grand living room with a working fireplace, private dining area, two full bedrooms and a dedicated butler on call throughout your stay.",
        price_per_night: 1650,
        max_occupancy: 4,
        adults: 3,
        children: 1,
        size_sqft: 1400,
        floor_level: "Floors 9–11",
        view_type: "Times Square Direct View",
        bed_type: "King + One Queen",
        bathroom_type:
          "Two luxury marble bathrooms, master with freestanding tub, dual rainfall showers, steam and heated floors",
        features: [
          "1,400 sq ft",
          "King + Queen Bedroom",
          "Grand Living Room",
          "Working Fireplace",
          "Private Dining Area",
          "Times Square View",
          "2 Marble Bathrooms",
          "Dual Rainfall Showers",
          "Steam Shower",
          "Freestanding Tub",
          "Heated Stone Floors",
          '85" 4K Smart TV x3',
          "Full Wet Bar",
          "Wine Fridge",
          "Nespresso Premium",
          "Safe",
          "Pillow Menu",
          "Dedicated Butler",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '85" 4K Smart TV x3',
          "Full Wet Bar",
          "Wine Fridge",
          "Nespresso Premium",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Dedicated Butler",
          "Working Fireplace",
          "Steam Shower",
          "Twice-daily Housekeeping",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=1200&q=85&fit=crop",
        ],
        is_featured: false,
      },
      {
        category_slug: "grand-suite",
        name: "Grand Terrace Suite",
        slug: "grand-terrace-suite",
        short_description:
          "Rare private terrace offering alfresco dining above Manhattan's skyline.",
        description:
          "One of only two suites in the hotel to feature a private outdoor terrace, the Grand Terrace Suite is an extraordinary find. Your personal outdoor space, furnished with teak chairs and a dining table, overlooks Manhattan's skyline. Inside, the suite delivers the full Grand standard — spacious living room, dining area and master bedroom with the finest appointments.",
        price_per_night: 1850,
        max_occupancy: 4,
        adults: 3,
        children: 1,
        size_sqft: 1350,
        floor_level: "Floor 10",
        view_type: "City Panoramic with Private Terrace",
        bed_type: "King",
        bathroom_type:
          "Two full marble bathrooms with freestanding tub, steam shower, dual vanity and heated floors",
        features: [
          "1,350 sq ft",
          "Private Outdoor Terrace",
          "King Bed",
          "Grand Living Room",
          "Dining Area",
          "City Panoramic Views",
          "2 Marble Bathrooms",
          "Freestanding Tub",
          "Steam Shower",
          "Heated Floors",
          '85" 4K Smart TV x3',
          "Full Wet Bar",
          "Outdoor Dining Furniture",
          "Nespresso Premium",
          "Safe",
          "Pillow Menu",
          "Dedicated Butler",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '85" 4K Smart TV x3',
          "Private Terrace",
          "Full Wet Bar",
          "Nespresso Premium",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Dedicated Butler",
          "Steam Shower",
          "Heated Floors",
          "Twice-daily Housekeeping",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
      {
        category_slug: "grand-suite",
        name: "Grand Penthouse Suite",
        slug: "grand-penthouse-suite",
        short_description:
          "Penthouse-level grandeur with sweeping views across all of Manhattan.",
        description:
          "Positioned on the uppermost residential floor, the Grand Penthouse Suite offers unrivalled elevation and horizon. Panoramic views span from Times Square to the Hudson River in one direction and Central Park to the Brooklyn skyline in the other. Designed for those who accept nothing short of the absolute best.",
        price_per_night: 2200,
        max_occupancy: 4,
        adults: 3,
        children: 1,
        size_sqft: 1600,
        floor_level: "Penthouse Floor (Floor 12)",
        view_type: "360° City, River, Park & Skyline Views",
        bed_type: "King Master + One King",
        bathroom_type:
          "Two palatial marble bathrooms, master with two freestanding tubs, dual rainfall showers, steam room and heated onyx floors",
        features: [
          "1,600 sq ft",
          "King Master Bedroom",
          "Second King Bedroom",
          "360° Views",
          "Grand Salon",
          "Dining Room (seats 8)",
          "2 Palatial Bathrooms",
          "Steam Room",
          "Dual Freestanding Tubs",
          "Heated Onyx Floors",
          '85" 4K Smart TV x4',
          "Full Wet Bar",
          "Champagne Fridge",
          "Nespresso Premium",
          "Safe",
          "Pillow Menu",
          "Dedicated Butler Team",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          '85" 4K Smart TV x4',
          "Full Wet Bar",
          "Champagne Fridge",
          "Nespresso Premium",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Dedicated Butler Team",
          "Steam Room",
          "Heated Onyx Floors",
          "Twice-daily Housekeeping",
          "Room Service 24/7",
          "Personal Concierge",
        ],
        images: [
          "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },

      // ── ADDITIONAL PRESIDENTIAL SUITES ───────────────────────────
      {
        category_slug: "presidential-suite",
        name: "Royal Suite",
        slug: "royal-suite",
        short_description:
          "Fit for royalty — an opulent two-bedroom residence of incomparable distinction.",
        description:
          "Fit for heads of state and the world's most discerning guests, the Royal Suite is a statement of aristocratic grandeur. Two king bedrooms, a formal reception room dressed with bespoke furnishings, a private study and two full marble bathrooms constitute a genuinely extraordinary residence within the heart of New York City.",
        price_per_night: 3200,
        max_occupancy: 4,
        adults: 4,
        children: 0,
        size_sqft: 2400,
        floor_level: "Floor 11–12",
        view_type: "Times Square & Hudson River Panoramic",
        bed_type: "Two King Bedrooms",
        bathroom_type:
          "Two full marble bathrooms, master with freestanding tub, dual rain showers, steam and heated stone floors",
        features: [
          "2,400 sq ft",
          "Two King Bedrooms",
          "Formal Reception Room",
          "Private Study",
          "Bespoke Furnishings",
          "Times Square & Hudson River Views",
          "2 Full Marble Bathrooms",
          "Freestanding Tub",
          "Dual Rain Showers",
          "Steam",
          "Heated Stone Floors",
          '85" 4K Smart TV x4',
          "Grand Piano",
          "Full Wet Bar",
          "Wine Cellar",
          "Nespresso Premium Bar",
          "Safe",
          "Pillow Menu",
          "Dedicated Butler Team",
          "Private Check-in",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          "Grand Piano",
          "Wine Cellar",
          "Full Wet Bar",
          "Nespresso Premium Bar",
          "Safe",
          "Complimentary Wi-Fi",
          "Pillow Menu",
          "Robes & Slippers",
          "Dedicated Butler Team",
          "Private Check-in",
          "Steam",
          "Heated Stone Floors",
          "24/7 Personal Concierge",
          "Room Service 24/7",
        ],
        images: [
          "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
      {
        category_slug: "presidential-suite",
        name: "Moxy Signature Suite",
        slug: "moxy-signature-suite",
        short_description:
          "The definitive Moxy address — a two-floor private residence of incomparable distinction.",
        description:
          "The Moxy Signature Suite is a two-floor private residence that represents the absolute pinnacle of what Moxy NYC Times Square can offer. A grand staircase connects the reception floor — complete with a formal dining room for twelve, a private screening room and a study — to the upper residential floor with three bedrooms, three full bathrooms and a private wraparound observation terrace. Reserved only for those who require the extraordinary.",
        price_per_night: 6500,
        max_occupancy: 8,
        adults: 6,
        children: 2,
        size_sqft: 5000,
        floor_level: "Floors 11–12 (Two-floor Residence)",
        view_type:
          "360° Panoramic — Times Square, Hudson River, Central Park, Manhattan",
        bed_type: "Three King Bedrooms + Bunk Cabin",
        bathroom_type:
          "Three full marble bathrooms + powder room, master with two freestanding tubs, dual rainfall showers, steam room, sauna and heated marble floors",
        features: [
          "5,000 sq ft",
          "Three King Bedrooms",
          "Bunk Cabin Room",
          "Private Grand Staircase",
          "Formal Dining Room (seats 12)",
          "Private Screening Room",
          "Private Study",
          "Wraparound Observation Terrace",
          "360° Panoramic Views",
          "3 Full Marble Bathrooms",
          "Private Sauna",
          "Steam Room",
          "Two Freestanding Tubs",
          "Heated Marble Floors",
          '85" 4K Smart TV x6',
          "Grand Piano",
          "Full Kitchen",
          "Wine Cellar",
          "Champagne Bar",
          "Dedicated Butler Team (3)",
          "Private Check-in Entrance",
          "Airport Limousine",
          "Personal Chef on Request",
          "Pillow Menu",
          "Complimentary Wi-Fi",
          "Robes & Slippers",
        ],
        amenities: [
          "Grand Piano",
          "Full Kitchen",
          "Wine Cellar",
          "Champagne Bar",
          "Private Sauna",
          "Steam Room",
          "Dedicated Butler Team",
          "Private Check-in",
          "Airport Limousine",
          '85" 4K Smart TV x6',
          "Personal Chef on Request",
          "Heated Marble Floors",
          "24/7 Personal Concierge",
          "Room Service 24/7",
          "Wraparound Terrace",
        ],
        images: [
          "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=85&fit=crop",
          "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1200&q=85&fit=crop",
        ],
        is_featured: true,
      },
    ];

    for (const r of rooms) {
      await client.query(
        `
        INSERT INTO rooms (
          category_id, name, slug, description, short_description,
          price_per_night, max_occupancy, adults, children,
          size_sqft, floor_level, view_type, bed_type, bathroom_type,
          features, amenities, images, is_featured, display_order
        ) VALUES (
          $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19
        ) ON CONFLICT (slug) DO UPDATE SET
          features = EXCLUDED.features,
          amenities = EXCLUDED.amenities,
          images = EXCLUDED.images,
          price_per_night = EXCLUDED.price_per_night,
          description = EXCLUDED.description,
          short_description = EXCLUDED.short_description,
          display_order = EXCLUDED.display_order,
          is_featured = EXCLUDED.is_featured;
      `,
        [
          catMap[r.category_slug],
          r.name,
          r.slug,
          r.description,
          r.short_description,
          r.price_per_night,
          r.max_occupancy,
          r.adults,
          r.children,
          r.size_sqft,
          r.floor_level,
          r.view_type,
          r.bed_type,
          r.bathroom_type,
          JSON.stringify(r.features),
          JSON.stringify(r.amenities),
          JSON.stringify(r.images),
          r.is_featured,
          rooms.indexOf(r) + 1,
        ],
      );
    }

    // Offers
    await client.query(`
      INSERT INTO offers (title, slug, description, short_description, promo_code, discount_type, discount_value, valid_from, valid_until, image_url, is_active, display_order)
      VALUES
        ('World Cup Luxury Package', 'world-cup-package', 'Celebrate the beautiful game in style. Our World Cup Luxury Package includes three nights in a Deluxe Room, daily breakfast for two, a curated match-viewing experience in our private lounge, and a welcome amenity upon arrival.', 'Three nights, breakfast for two, private match viewing.', 'WORLDCUP2026', 'percentage', 15, '2026-05-01', '2026-12-31', 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=900&q=85&fit=crop', true, 1),
        ('Bed & Breakfast Retreat', 'bed-and-breakfast', 'Begin each morning with a full gourmet breakfast at The Loft Restaurant, served amid the vibrant energy of Moxy NYC''s dining room. Available with any room category.', 'Room + daily gourmet breakfast for two.', 'BBMOXY', 'fixed', 65, '2026-01-01', '2026-12-31', 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=900&q=85&fit=crop', true, 2),
        ('Romance in the City', 'romance-package', 'Arrive to a room dressed with rose petals, Veuve Clicquot Champagne, and hand-selected confections. Includes a couples spa treatment and a candlelit dinner reservation at The Loft Restaurant.', 'Champagne, roses, couples spa, and dinner.', 'ROMANCE', 'fixed', 0, '2026-01-01', '2026-12-31', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=900&q=85&fit=crop', true, 3),
        ('The Long Weekend Escape', 'long-weekend', 'Stay three or more nights and receive a 20% reduction across all room categories. Ideal for extended discovery of New York City and its world-class neighbourhoods.', '20% off for stays of 3 nights or more.', 'LONGWEEKEND', 'percentage', 20, '2026-01-01', '2026-12-31', 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=900&q=85&fit=crop', true, 4)
      ON CONFLICT (slug) DO UPDATE SET image_url = EXCLUDED.image_url;
    `);

    // Blog posts
    await client
      .query(
        `
      SELECT id FROM users WHERE email = 'admin@fifahotel.com' LIMIT 1
    `,
      )
      .then(async ({ rows }) => {
        if (rows.length) {
          const authorId = rows[0].id;
          await client.query(
            `
          INSERT INTO blog_posts (title, slug, excerpt, body, author_id, category, tags, cover_image, is_published, published_at)
          VALUES
            ('New York City in Spring: What to See and Do Near Moxy NYC', 'nyc-spring-guide-2026', 'Spring in New York City is a celebration of energy, culture, and renewal. From the blooming paths of Central Park to the electric pulse of Times Square, the city offers an unrivalled backdrop for a luxury getaway.', '<p>Spring in New York City...</p>', $1, 'Travel Guides', '["New York","Spring","Travel","Times Square"]', 'https://images.unsplash.com/photo-1521747116042-5a810fda9664?w=1200&q=85&fit=crop', true, NOW()),
            ('Moxy NYC Times Square: Redefining Urban Luxury Since 1996', 'moxy-nyc-history', 'Since opening its doors in 1996, Moxy NYC Times Square has stood as a beacon of bold hospitality in the heart of New York City. From celebrity stays to iconic events, our story is woven into the fabric of Times Square itself.', '<p>The Moxy NYC story begins...</p>', $1, 'Hotel News', '["History","Moxy NYC","Heritage","Times Square"]', 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=1200&q=85&fit=crop', true, NOW()),
            ('The 2026 FIFA World Cup: New York City''s Moment to Shine', 'fifa-world-cup-2026-nyc', 'With New York City hosting matches in the 2026 FIFA World Cup, Times Square has become one of the most sought-after destinations for football fans from around the world. Here is how Moxy NYC Times Square is celebrating.', '<p>The World Cup arrives...</p>', $1, 'Hotel News', '["World Cup","Football","FIFA 2026","Events"]', 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&q=85&fit=crop', true, NOW())
          ON CONFLICT (slug) DO UPDATE SET cover_image = EXCLUDED.cover_image;
        `,
            [authorId],
          );
        }
      });

    // Approved reviews
    await client.query(`
      INSERT INTO reviews (guest_name, rating, title, body, is_approved)
      VALUES
        ('James & Catherine H.', 5, 'The finest hotel experience of our lives', 'From the moment we arrived, every detail was attended to with a grace and professionalism that is vanishingly rare. The Grand Moxy Suite exceeded every expectation. New York City is the better for having this extraordinary property.', true),
        ('Ambassador R. Dupont', 5, 'Unrivalled in elegance and service', 'I have stayed in the world''s greatest hotels over four decades of diplomatic service. Moxy NYC Times Square remains, without qualification, among the very finest. The attentiveness of staff and the energy of the property are simply extraordinary.', true),
        ('Dr. Priya Mehta', 5, 'A perfect setting for our anniversary', 'We chose the Romance Package for our tenth anniversary and were moved by the care taken with every element — the flowers, the champagne, the dinner. The staff made us feel like the only guests in the hotel.', true),
        ('Marcus T.', 5, 'The Times Square View room was breathtaking', 'Waking up to a direct view of Times Square from bed is something I will not forget. The room was immaculate, the breakfast at The Loft Restaurant was superb, and the concierge found us theatre tickets at the last minute. Impeccable.', true),
        ('The Chen Family', 5, 'We will return every year', 'Travelling with children can be challenging, but the team here managed to make every member of our family feel at home. The pool, the dining, the rooms — everything is at the absolute peak of quality.', true)
      ON CONFLICT DO NOTHING;
    `);

    await client.query("COMMIT");
    console.log("Seed completed successfully.");
  } catch (err) {
    await client.query("ROLLBACK");
    console.error("Seed failed:", err);
    throw err;
  } finally {
    if (isDirectClient) {
      await client.end();
    } else {
      client.release();
      await pool.end();
    }
  }
};

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
