export const SITE_CONFIG = {
  name: "Moxy NYC Times Square",
  tagline: "Where Energy Meets Elegance",
  domain: "fifahotel.com",
  url: "https://fifahotel.com",
  address: {
    street: "485 7th Ave",
    city: "New York",
    province: "NY",
    postalCode: "10018",
    country: "United States",
    full: "485 7th Ave, New York, NY 10018, United States",
  },
  contact: {
    phone: "+1 (914) 432-9936",
    email: "support@fifahotel.com",
    support: "support@fifahotel.com",
    reservations: "support@fifahotel.com",
    fax: "+1 (212) 967-6401",
  },
  social: {
    instagram: "https://instagram.com/moxynytimessquare",
    facebook: "https://facebook.com/moxynytimessquare",
    twitter: "https://twitter.com/moxynytimessq",
    linkedin: "https://linkedin.com/company/moxy-nyc-times-square",
    youtube: "https://youtube.com/@moxynytimessquare",
  },
  hours: {
    frontDesk: "24 hours, 7 days a week",
    spa: "6:00 AM – 10:00 PM",
    restaurant: "6:30 AM – 10:30 PM",
    bar: "12:00 PM – 2:00 AM",
    pool: "6:00 AM – 10:00 PM",
    fitness: "5:00 AM – 11:00 PM",
  },
  bankDetails: {
    bankName: "JPMorgan Chase",
    accountName: "Moxy NYC Times Square LLC",
    accountNumber: "XXXX-XXXX-XXXX",
    routingNumber: "XXXXXXXXX",
    swiftCode: "CHASUS33",
    iban: "XXXXXXXXXXXXXXXXXX",
    instructions:
      "Please include your Booking Reference Number as the payment reference.",
  },
  meta: {
    foundedYear: 1996,
    stars: 5,
    totalRooms: 429,
  },
};
